# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fYec7TJA7WJhyTZSECS3FnTSFCJEhOfz
"""

#Ejercicio clase 29 de septiembre "2023"
with open('gramatica.txt', 'r') as file:
    lines = file.readlines()

#componentes en lista
non_terminals = []
rhs = []
lhs = []

#proceso
for line in lines:
    line = line.strip().split()
    lhs.append(line[0])
    rhs.append(line[1:])


    if line[0] not in non_terminals:
        non_terminals.append(line[0])

print("Componentes NT (No Terminales):", non_terminals)


print("\nReglas Gramaticales:")
for i in range(len(lhs)):
    print(f"{lhs[i]} -> {' '.join(rhs[i])}")

print("\nInformación sobre MAX# y FIRST:")
for i in range(len(lhs)):
    max_options = len(rhs[i])
    first_set = rhs[i][0] if max_options > 0 else "ε"
    print(f"{lhs[i]}: MAX#: {max_options}, FIRST: {first_set}")